---
- hosts: web
  
  tasks:

    - name: install httpd*
      yum: name=httpd state=latest


    - name: (Enable it on System Boot)
      service: name=httpd enabled=yes

    - name: start apache
      service: name=httpd state=started

    - name: Copying the demo file
      template: src=~/apache/index.html.j2 dest=/var/www/example.com/public_html/index.html

    - name: Copying the demo file
      template: src=~/apache/example.com.conf.j2 dest=/etc/httpd/conf.d/example.com.conf

    
    - name: restart apache
      service: name=httpd state=restarted

