---
- hosts: haproxy
  
  tasks:

    - name: install haproxy
      yum: name=haproxy state=latest


    - name: (Enable it on System Boot)
      service: name=haproxy enabled=yes

    - name: start haproxy
      service: name=haproxy state=started

    - name: Copying the conf file
      template: src=~/haproxy/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

    - name: Copying the host file
      template: src=~/haproxy/hosts.j2 dest=/etc/hosts


    - name: restart haproxy
      service: name=haproxy state=restarted

    - name: desactiver SElinux
      template: src=~/haproxy/selinux.j2 dest=/etc/sysconfig/selinux

#    - name: reboot server
#      reboot:
